---
name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Update apt repository
        run: sudo apt update
      - name: Install apt dependencies
        run: sudo apt install --yes apparmor-utils libsasl2-dev python-dev-is-python3 libldap2-dev libssl-dev slapd ldap-utils
      - name: App armor configuration for slapd
        run: sudo aa-complain /usr/sbin/slapd
      - name: Install python dependencies
        run: pip install tox poetry
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
